# This file is used to run a Vertex AI job from the command line:
# gcloud ai custom-jobs create \
    # --region=europe-west1 \
    # --display-name=test-run \
    # --config=cloud_config_train.yaml

workerPoolSpecs:
    machineType: n1-standard-8
        acceleratorType: NVIDIA_TESLA_T4 
        acceleratorCount: 1
    replicaCount: 1
    containerSpec:
        imageUri: gcr.io/enzyme-stability-02476/train_model