hyperparameters:
  lr: 0.001
  batch_size: 50
  epochs: 1
  hidden1: 1024
  hidden2: 1024
  num_workers: 3
seed: 42
data_path: "gs://protein_embeddings/data/processed"
criterion: "MSELoss"
optimizer: "Adam"
runname: "test_170124"
checkpoint_path: "gs://dtu-mlops-storage/models/MLP/checkpoints/"
BERT_path: "mlops_enzyme_stability/models/protBERT/"
project_name: "lightning_logs"
bucket_name: "dtu-mlops-storage"
wandb_api_key: 7739e5ac7ba13684763d4284b6c4080944145f2f
best_model_name: "test3"
