config:
  hyperparameters:
    lr: 0.001
    batch_size: 16
    epochs: 1
    hidden1: 512
    hidden2: 256
    num_workers: 3
  data_path: data/processed
  criterion: MSELoss
  optimizer: Adam
  runname: test1
  checkpoint_path: mlops_enzyme_stability/models/checkpoints
