hyperparameters:
  lr: 0.001
  batch_size: 16
  epochs: 1
  hidden1: 512
  hidden2: 256
  num_workers: 3
seed: 42
gs_project_name: "enzyme-stability-02476"
gs_bucket_name: "dtu-mlops-storage"
criterion: "MSELoss"
optimizer: "Adam"
runname: "model_170224"