hyperparameters:
  lr: 0.001
  batch_size: 16
  epochs: 1
  hidden1: 512
  hidden2: 256
  num_workers: 3
seed: 42
data_path: "gs://protein_embeddings/data/processed"
criterion: "MSELoss"
optimizer: "Adam"
runname: "test3"
checkpoint_path: "mlops_enzyme_stability/models/checkpoints/"
BERT_path: "mlops_enzyme_stability/models/protBERT/"
project_name: "lightning_logs"