hyperparameters:
  lr: 0.001
  batch_size: 16
  epochs: 1
  hidden1: 512
  hidden2: 256
  num_workers: 3
data_path: "data/processed"
criterion: "MSELoss"
optimizer: "Adam"
runname: "test1"
checkpoint_path: "C:/Users/Anders/OneDrive - Danmarks Tekniske Universitet/DTU/5. Semester - UCSD/02476 - Machine Learning Operations/02476_enzyme_stability/models/"